// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mp3tags/gateway-user/models"
)

// PostAPIV1UploadOKCode is the HTTP code returned for type PostAPIV1UploadOK
const PostAPIV1UploadOKCode int = 200

/*PostAPIV1UploadOK Succesful

swagger:response postApiV1UploadOK
*/
type PostAPIV1UploadOK struct {

	/*
	  In: Body
	*/
	Payload *models.UploadResponse `json:"body,omitempty"`
}

// NewPostAPIV1UploadOK creates PostAPIV1UploadOK with default headers values
func NewPostAPIV1UploadOK() *PostAPIV1UploadOK {

	return &PostAPIV1UploadOK{}
}

// WithPayload adds the payload to the post Api v1 upload o k response
func (o *PostAPIV1UploadOK) WithPayload(payload *models.UploadResponse) *PostAPIV1UploadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post Api v1 upload o k response
func (o *PostAPIV1UploadOK) SetPayload(payload *models.UploadResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAPIV1UploadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAPIV1UploadBadRequestCode is the HTTP code returned for type PostAPIV1UploadBadRequest
const PostAPIV1UploadBadRequestCode int = 400

/*PostAPIV1UploadBadRequest Bad Request

swagger:response postApiV1UploadBadRequest
*/
type PostAPIV1UploadBadRequest struct {
}

// NewPostAPIV1UploadBadRequest creates PostAPIV1UploadBadRequest with default headers values
func NewPostAPIV1UploadBadRequest() *PostAPIV1UploadBadRequest {

	return &PostAPIV1UploadBadRequest{}
}

// WriteResponse to the client
func (o *PostAPIV1UploadBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostAPIV1UploadInternalServerErrorCode is the HTTP code returned for type PostAPIV1UploadInternalServerError
const PostAPIV1UploadInternalServerErrorCode int = 500

/*PostAPIV1UploadInternalServerError Internal error

swagger:response postApiV1UploadInternalServerError
*/
type PostAPIV1UploadInternalServerError struct {
}

// NewPostAPIV1UploadInternalServerError creates PostAPIV1UploadInternalServerError with default headers values
func NewPostAPIV1UploadInternalServerError() *PostAPIV1UploadInternalServerError {

	return &PostAPIV1UploadInternalServerError{}
}

// WriteResponse to the client
func (o *PostAPIV1UploadInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
