// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostAPIV1UploadHandlerFunc turns a function with the right signature into a post API v1 upload handler
type PostAPIV1UploadHandlerFunc func(PostAPIV1UploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAPIV1UploadHandlerFunc) Handle(params PostAPIV1UploadParams) middleware.Responder {
	return fn(params)
}

// PostAPIV1UploadHandler interface for that can handle valid post API v1 upload params
type PostAPIV1UploadHandler interface {
	Handle(PostAPIV1UploadParams) middleware.Responder
}

// NewPostAPIV1Upload creates a new http.Handler for the post API v1 upload operation
func NewPostAPIV1Upload(ctx *middleware.Context, handler PostAPIV1UploadHandler) *PostAPIV1Upload {
	return &PostAPIV1Upload{Context: ctx, Handler: handler}
}

/*PostAPIV1Upload swagger:route POST /api/v1/upload postApiV1Upload

upload file to server

*/
type PostAPIV1Upload struct {
	Context *middleware.Context
	Handler PostAPIV1UploadHandler
}

func (o *PostAPIV1Upload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostAPIV1UploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
