// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi mp3tags
Mp3tag service. You can find out more at [http://mp3tags.org](http://mp3tags.org)


    Schemes:
      http
    Host: mp3tags.org
    BasePath: /api/v1
    Version: 0.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
